### ISSUE TITLE
「I H R は 寝 て ろ ！ ！」機能

### ISSUE THREAD

**Issue by jfsso** [f110/go-imghr#15]
毎日14:00 ~ 17:00 の間にihrがtyping状態になった時に、すぐさま「I H R は 寝 て ろ ！ ！」と自動投稿する。１回以上言われると(´・ω・｀)ｼｮﾎﾞｰﾝってなりそうだから、１日に１回だけ投稿する。

**Comment by f110** [comment]
> １日に１回だけ投稿する。

永続化するのめんどい。
プロセスの再起動でフラグが失われるくらいで妥協したい

**Comment by jfsso** [comment]
いいと思います! :+1:

**Comment by f110** [comment]
実装した。明日試す。
